- README.md
1. update readme, add source code integration method
> chore: update readme to add source code integration method

- README.md
- package.json
- src/provider/ClickstreamProvider.ts
- src/tracker/ClickTracker.ts
- src/tracker/PageViewTracker.ts
- src/types/Analytics.ts
- test/ClickstreamAnalytics.test.ts
- test/tracker/ClickTracker.test.ts
1. add publish configure
2. fix redundant click event 
3. support domain list configure
> feat: add publish configure, fix redundant click event

- README.md
- package.json
1. update sdk init code in readme
> fix: update readme for sdk init

- README.md
- src/provider/AnalyticsEventBuilder.ts
- src/provider/ClickstreamProvider.ts
- src/provider/Event.ts
- src/provider/EventChecker.ts
- src/provider/index.ts
- src/tracker/ClickTracker.ts
- src/types/Analytics.ts
- test/ClickstreamAnalytics.test.ts
- test/provider/AnalyticsEventBuilder.test.ts
- test/provider/EventChecker.test.ts
- test/provider/EventRecorder.test.ts
- test/tracker/ClickTracker.test.ts
1. support items record
2. fix `_click` event lose when wrapped multiple element layer
> feat: support items record

- src/browser/BrowserInfo.ts
- src/provider/AnalyticsEventBuilder.ts
- src/provider/Event.ts
- test/browser/BrowserInfo.test.ts
- test/provider/AnalyticsEventBuilder.test.ts
> feat: support latest referrer

- .github/workflows/release.yml
- release.sh
- tsconfig.json
1. Add release new version action
> ci: add release new version action

- src/provider/Event.ts
- src/tracker/SessionTracker.ts
- test/tracker/SessionTracker.test.ts
> feat: add app end preset event

- README.md
- src/index.ts
1. add export type for item
2. update doc for item record
> feat: add export type for item

- src/types/Analytics.ts
- test/provider/EventRecorder.test.ts
1. change the type of price in item 
2. add attribute currency to item
> feat: change the type of price in item and add currency to item

- src/network/NetRequest.ts
- src/provider/AnalyticsEventBuilder.ts
- src/provider/ClickstreamProvider.ts
- src/provider/Event.ts
- src/types/Analytics.ts
- test/ClickstreamAnalytics.test.ts
- test/network/NetRequest.test.ts
- test/provider/AnalyticsEventBuilder.test.ts
- test/provider/BatchModeTimer.test.ts
- test/provider/ClickstreamProvider.test.ts
- test/provider/EventRecorder.test.ts
- test/provider/ImmediateModeCache.test.ts
- test/tracker/PageViewTracker.test.ts
- test/tracker/SessionTracker.test.ts
1. delete hashCode form each event attribute
2. add hashCode into request query parameter
> feat: add hash code to request query parameter

- src/tracker/PageViewTracker.ts
- test/tracker/PageViewTracker.test.ts
1. optimize user engagement event record logic.
> chore: optimize user engagement event record logic

- src/provider/AnalyticsEventBuilder.ts
- test/provider/AnalyticsEventBuilder.test.ts
1. fixed global attribute values being affected when checking event attributes
> fix: global attribute values being affected when checking event attributes

- src/tracker/SessionTracker.ts
- test/tracker/SessionTracker.test.ts
1. fix multi page mode app start event redundant logging
> fix: multi page mode app start event redundant logging

- .github/workflows/title-lint.yml
1. update title lint action and allow PR by dependabot
> ci: update title lint action and allow PR via dependabot

- README.md
fix: readme global attribute code alignment
> chore: readme global attribute code alignment

- README.md
1. update doc link
2. update items
> fix: update items and doc link in readme

- src/provider/EventChecker.ts
- test/provider/AnalyticsEventBuilder.test.ts
1. fix items check error when attribute value is undefined or null
> fix: items check error when attribute value is undefined or null

- README.md
- src/provider/ClickstreamProvider.ts
- src/tracker/SessionTracker.ts
- src/types/Analytics.ts
- test/provider/ImmediateModeCache.test.ts
- test/tracker/SessionTracker.test.ts
1. support configure tracking app start and app end events
> feat: support configure tracking _app_start and _app_end events

- src/tracker/Session.ts
- src/tracker/SessionTracker.ts
- src/util/StorageUtil.ts
- test/tracker/SessionTracker.test.ts
1. fix sessionId in first open and session start events
> fix: sessionId in first open and session start events

- src/network/NetRequest.ts
- test/network/NetRequest.test.ts
1. add upload_timestamp to calibrate local timestamp
> feat: support calibrate local timestamp

- src/tracker/SessionTracker.ts
- test/tracker/SessionTracker.test.ts
1. fix idle duration not updated when user hides page
> fix: idle duration not updated when user hides page

- package-lock.json
- test/browser/BrowserInfo.test.ts
- test/tracker/PageViewTracker.test.ts
1.  bump npm packages for security
> chore: bump npm packages for security

- package-lock.json
> chore: bump ws and braces

- src/network/NetRequest.ts
1. add credentials attribute and support cross domain cookie
> fix: add credentials attribute and support cross domain cookie 

- CHANGELOG.md
- README.md
- buildspec.yml
- package-lock.json
- package.json
- solution-manifest.yaml
*Issue #, if available:*
*Description of changes:*
* Patch security vulnerability CVE-2025-7783
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> Changes for v0.12.6
